apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-service
spec:
  selector:
    app: redis-sentinel
  ports:
  - port: 26379
    targetPort: 26379