apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: saleor-instrumentation
spec:
  exporter:
    endpoint: http://higiliquidos-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  env:
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_LOG_LEVEL
      value: "debug"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp" 
    - name: OTEL_METRICS_EXPORTER
      value: "otlp"
  python:
    image: k3d-higiliqs.local:12345/autoinstrumentation-python:0.54b1
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://higiliquidos-collector:4318"
      - name: DJANGO_SETTINGS_MODULE
        value: saleor.settings
      - name: OTEL_TRACES_EXPORTER
        value: otlp_proto_http
      - name: OTEL_METRICS_EXPORTER
        value: "otlp_proto_http"
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: worker-instrumentation
spec:
  exporter:
    endpoint: http://higiliquidos-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  env:
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_LOG_LEVEL
      value: "debug"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_METRICS_EXPORTER
      value: "otlp"
  python:
    image: k3d-higiliqs.local:12345/autoinstrumentation-python:0.54b1
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://higiliquidos-collector:4318"
      - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
        value: django
      - name: OTEL_TRACES_EXPORTER
        value: otlp_proto_http
      - name: OTEL_METRICS_EXPORTER
        value: "otlp_proto_http"
      - name: OTEL_PYTHON_LOG_LEVEL
        value: "debug"
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: payments-instrumentation
spec:
  exporter:
    endpoint: http://higiliquidos-collector:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  env:
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_LOG_LEVEL
      value: "debug"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_METRICS_EXPORTER
      value: "otlp"
  nodejs:
    image: k3d-higiliqs.local:12345/autoinstrumentation-nodejs:0.58.1
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://higiliquidos-collector:4318"
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: stf-instrumentation
spec:
  exporter:
    endpoint: http://higiliquidos-collector:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  env:
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_LOG_LEVEL
      value: "debug"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp" 
    - name: OTEL_METRICS_EXPORTER
      value: "otlp"
  nodejs:
    image: k3d-higiliqs.local:12345/autoinstrumentation-nodejs:0.58.1
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://higiliquidos-collector:4318"