kind: pipeline
type: kubernetes
name: build-and-push

steps:
- name: build and push
  image: docker:dind
  volumes:
  - name: dockersock 
    path: /var/run
  commands:
    - sleep 5
    - docker build -f repos/saleor-dashboard/Dockerfile -t k3d-registry.higiliquidos.svc.cluster.local:12345/saleor-dashboard:3.20.34 .
    - docker push k3d-registry.higiliquidos.svc.cluster.local:12345/saleor-dashboard:3.20.34

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  command: ["--insecure-registry", "k3d-registry.higiliquidos.svc.cluster.local:12345"]


volumes:
- name: dockersock 
  temp: {}
