kind: pipeline
type: kubernetes
name: build-and-push

steps:
- name: build and push
  image: docker:dind
  volumes:
  - name: dockersock 
    path: /var/run
  commands:
    - sleep 5
    - cd repos/storefront
    - docker build --build-arg NEXT_PUBLIC_SALEOR_API_URL=http://saleor-api.higiliquidos.svc.cluster.local/graphql/ --build-arg NEXT_PUBLIC_STOREFRONT_URL=http://store.higiliquidos.deti.com/ -f Dockerfile -t k3d-registry.higiliquidos.svc.cluster.local:12345/saleor-storefront:0.2.0 .
    - docker push k3d-registry.higiliquidos.svc.cluster.local:12345/saleor-storefront:0.2.0

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  command: ["--insecure-registry", "k3d-registry.higiliquidos.svc.cluster.local:12345"]

volumes:
- name: dockersock 
  temp: {}