apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: cluster-secrets
  type: Opaque
  envs:
  - .env
- name: saleor-secrets
  type: Opaque
  envs:
  - .env.saleor

resources:
  - ../../base