apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: cluster-secrets
  type: Opaque
  envs:
  - .env

- name: exporter-secrets
  type: Opaque
  envs:
  - .env.exporters

- name: saleor-secrets
  type: Opaque
  envs:
  - .env.saleor
  files:
    - RSA_PRIVATE_KEY=RSA_PRIVATE_KEY.pem

- name: saleor-dashboard-secrets
  type: Opaque
  envs:
  - .env.saleor-dashboard

resources:
  - ../../base

images:
  - name: k3d-higiliqs.local:12345/saleor
    newTag: "3.20.80"
  - name: k3d-higiliqs.local:12345/saleor-dashboard
    newTag: "3.20.34"
  - name: k3d-higiliqs.local:12345/storefront
    newTag: "0.1.0"