apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: k3d-registry.higiliquidos.svc.cluster.local:12345/saleor
    newTag: "3.20.80"
  - name: k3d-registry.higiliquidos.svc.cluster.local:12345/saleor-dashboard
    newTag: "3.20.34"
  - name: k3d-registry.higiliquidos.svc.cluster.local:12345/storefront
    newTag: "0.1.0"
