apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: saleor
    newName: k3d-registry.higiliquidos.svc.cluster.local:12345/saleor
    newTag: 3.20.80
  - name: dash
    newName: k3d-registry.higiliquidos.svc.cluster.local:12345/saleor-dashboard
    newTag: 3.20.34
  - name: storefront
    newName: k3d-registry.higiliquidos.svc.cluster.local:12345/storefront
    newTag: 0.1.0
  - name: k3d-registry.higiliquidos.svc.cluster.local:12345/saleor-dashboard
    newTag: 3.20.34
