apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: saleor-config
    envs:
      - common.env

resources:
- saleor-dep.yml
- saleor-worker.yml
- saleor-svc.yml
- saleor-job.yml
- saleor-ingress.yml