apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-api
  template:
    metadata:
      labels:
        app: saleor-api
    spec:
      initContainers:
      - name: wait-for-saleor-setup
        image: bitnami/kubectl:latest
        command: ['sh', '-c', 
          'until kubectl get job saleor-setup -n higiliquidos -o jsonpath="{.status.conditions[?(@.type==\"Complete\")].status}" | grep -q True; do echo waiting for saleor-setup job; sleep 5; done;']
      containers:
        - name: api
          image: k3d-higiliqs.local:12345/saleor:3.20.80
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          envFrom:
          - configMapRef:
              name: saleor-config
          - secretRef:
              name: saleor-secrets