apiVersion: v1
kind: Service
metadata:
  name: saleor-external
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: saleor-api
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-api
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: saleor-api