apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-api
  template:
    metadata:
      labels:
        app: saleor-api
    spec:
      initContainers:
      - name: wait-for-saleor-setup
        image: k3d-higiliqs.local:12345/kubectl:1.32.3
        command: ['sh', '-c', 
          'until kubectl get job saleor-setup -n higiliquidos -o jsonpath="{.status.conditions[?(@.type==\"Complete\")].status}" | grep -q True; do echo waiting for saleor-setup job; sleep 5; done;']
      containers:
        - name: api
          image: k3d-higiliqs.local:12345/saleor:3.20.80
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "700m"
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 10
          envFrom:
          - configMapRef:
              name: saleor-config
          - secretRef:
              name: saleor-secrets
          env:
            - name: ALLOWED_CLIENT_HOSTS
              value: "payments-api.higiliquidos.svc.cluster.local,saleor-api.higiliquidos.svc.cluster.local,dash.higiliquidos.deti.com,localhost,127.0.0.1,store.higiliquidos.deti.com,storefront,saleor-api,api.higiliquidos.deti.com,saleor-api"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://payments-api.higiliquidos.svc.cluster.local,http://saleor-api.higiliquidos.svc.cluster.local,http://dash.higiliquidos.deti.com,http://localhost:9000,http://store.higiliquidos.deti.com,http://storefront:3000,http://saleor-api"
            - name: ALLOWED_HOSTS
              value: "payments-api.higiliquidos.svc.cluster.local,saleor-api.higiliquidos.svc.cluster.local,dash.higiliquidos.deti.com,localhost,127.0.0.1,store.higiliquidos.deti.com,storefront,saleor-api, api.higiliquidos.deti.com,saleor-api"
