apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saleor-api
  template:
    metadata:
      labels:
        app: saleor-api
      annotations:
        instrumentation.opentelemetry.io/inject-python: "saleor-instrumentation" 
    spec:
      initContainers:
      - name: wait-for-saleor-setup
        image: k3d-higiliqs.local:12345/kubectl:1.32.3
        command: ['sh', '-c', 
          'until kubectl get job saleor-setup -n higiliquidos -o jsonpath="{.status.conditions[?(@.type==\"Complete\")].status}" | grep -q True; do echo waiting for saleor-setup job; sleep 5; done;']
      containers:
        - name: api
          image: k3d-higiliqs.local:12345/saleor:3.20.80
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "2048Mi"
              cpu: "1000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 10
          envFrom:
          - configMapRef:
              name: saleor-config
          - secretRef:
              name: saleor-secrets
          env: 
            - name: DJANGO_SETTINGS_MODULE
              value: saleor.settings
            - name: PYTHONPATH
              value: /app