apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: higiliquidos-project
  labels:
    app: higiliquidos
spec:
  # Project description
  description: Our ArgoCD Project to deploy our app locally
  # Allow manifests to deploy only from Sokube git repositories
  sourceRepos:
  - "https://github.com/GoncaloMark/*"
  # Only permit to deploy applications in the same cluster
  destinations:
  - namespace: higiliquidos
    server: https://kubernetes.default.svc
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false