apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup-cron-job
spec:
  schedule: "0 8,20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgresql-backup-job-pod
            image: k3d-higiliqs.local:12345/bckpg:0.1.0
            env:
              - name: PGHOST
                valueFrom:
                  secretKeyRef:
                    key: PG_HOST
                    name: cluster-secrets
              - name: PGUSER
                valueFrom:
                  secretKeyRef:
                    key: PG_USER
                    name: cluster-secrets
              - name: PGDATABASE
                valueFrom:
                  secretKeyRef:
                    key: PG_DB
                    name: cluster-secrets
              - name: PGPORT
                valueFrom:
                  secretKeyRef:
                    key: PG_PORT
                    name: cluster-secrets
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    key: PG_PASSWORD
                    name: cluster-secrets
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: AWS_ACCESS_KEY_ID
                    name: saleor-secrets
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    key: AWS_SECRET_ACCESS_KEY
                    name: saleor-secrets
              - name: S3_BUCKET
                value: "pg-backup"
            imagePullPolicy: Always
            args:
            - /bin/bash
            - -c
            - cd /home/root; ls; bash backup-pg.sh;
          restartPolicy: OnFailure
      backoffLimit: 3