apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: postgres
  files:
  - config/postgres.conf
  - config/master.conf
  - config/replica.conf
  - config/pg_hba.conf
  - config/create-replica-user.sh

resources:
- master-sts.yml
- replica-sts.yml
- pg-svc.yml
- pool-configmap.yml
- pool-dep.yml
- pool-svc.yml