apiVersion: v1
kind: ConfigMap
metadata:
  name: pgpool-config
  labels:
    app: pgpool-config
data:
  pgpool.conf: |-
    listen_addresses = '*'
    port = 5432
    socket_dir = '/var/run/pgpool'
    pcp_listen_addresses = '*'
    pcp_port = 9898
    pcp_socket_dir = '/var/run/pgpool'
    backend_hostname0 = 'postgres'  # Master
    backend_port0 = 5432
    backend_weight0 = 1
    backend_flag0 = 'ALWAYS_PRIMARY|DISALLOW_TO_FAILOVER'

    backend_hostname1 = 'postgres-replica'  # Replica 1
    backend_port1 = 5432
    backend_weight1 = 2
    backend_flag1 = 'DISALLOW_TO_FAILOVER'

    backend_hostname2 = 'postgres-replica'  # Replica 2
    backend_port2 = 5432
    backend_weight2 = 3
    backend_flag2 = 'DISALLOW_TO_FAILOVER'

    health_check_period = 0
    master_slave_mode = on
    backend_clustering_mode = 'streaming_replication'
    num_init_children = 5000
    max_pool = 4
    child_life_time = 300
    child_max_connections = 0
    connection_life_time = 0
    client_idle_limit = 0
    connection_cache = on
    load_balance_mode = on
    ssl = off
    enable_pool_hba = on
    failover_on_backend_error = off
    log_min_messages = warning
    sr_check_period = 10
    sr_check_user = 'replication'
    log_destination = 'stderr'
    black_function_list = 'nextval,setval,lastval,currval'
    statement_level_load_balance = on
    disable_load_balance_on_write = trans_transaction
    relcache_size = 1024
    log_per_node_statement = on
    log_disconnections = off
    log_statement = on