kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubectl-service-access
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubectl-service-access-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: higiliquidos
roleRef:
  kind: ClusterRole
  name: kubectl-service-access
  apiGroup: rbac.authorization.k8s.io
