apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: stf-instrumentation
  namespace: higiliquidos
spec:
  exporter:
    endpoint: http://higiliquidos-collector:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  nodejs:
    image: k3d-higiliqs.local:12345/autoinstrumentation-nodejs:0.58.1
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://higiliquidos-collector:4318"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storefront
  template:
    metadata:
      labels:
        app: storefront
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "stf-instrumentation" 
    spec:
      restartPolicy: Always
      initContainers:
      - name: wait-for-saleor-setup
        image: k3d-higiliqs.local:12345/kubectl:1.32.3
        command: ['sh', '-c', 
          'until kubectl get job saleor-setup -n higiliquidos -o jsonpath="{.status.conditions[?(@.type==\"Complete\")].status}" | grep -q True; do echo waiting for saleor-setup job; sleep 5; done;']
      containers:
        - name: storefront
          image: k3d-higiliqs.local:12345/saleor-storefront:0.1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            timeoutSeconds: 10
          ports:
            - containerPort: 3000
          # env:
          #   - name: NEXT_PUBLIC_SALEOR_API_URL
          #     value: "http://host.k3d.internal:8000/graphql/"
