apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - collector.yml
  - loki.yml
  - jaeger.yml
  - grafana.yml
  - prometheus.yml 
  - promtail.yml
  - exporters.yml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/pg_dash.json
      - dashboards/redis_dash.json
      - dashboards/saleor_dash.json
      - dashboards/celery_dash.json

  - name: grafana-dashboards-config
    files:
      - dashboards.yml

generatorOptions:
  disableNameSuffixHash: true
